// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/umic-landing/AttendeeSignal.tsx": () => import("../components/mockups/umic-landing/AttendeeSignal.tsx"),
  "./components/mockups/umic-landing/BroadcastPro.tsx": () => import("../components/mockups/umic-landing/BroadcastPro.tsx"),
  "./components/mockups/umic-landing/LiveRoom.tsx": () => import("../components/mockups/umic-landing/LiveRoom.tsx")
};
